services:
  postgres-dev:
    image: postgres
    environment:
      POSTGRES_USER: david123car7
      POSTGRES_PASSWORD: kazzio 
      POSTGRES_DB: cpp-rest-api-db
    ports:
      - "5432:5432"
  postgres-tests:
    image: postgres
    environment:
      POSTGRES_USER: test 
      POSTGRES_PASSWORD: test 
      POSTGRES_DB: cpp-rest-api-db-tests
    ports:
      - "5433:5432"
