DROP DATABASE IF EXISTS fleet-manager-db;

CREATE SCHEMA if NOT EXISTS public;

CREATE TABLE IF NOT EXISTS users (
  id UUID PRIMARY KEY, 
  email VARCHAR(255) UNIQUE NOT NULL,
  password TEXT NOT NULL
);
